<?php
return $apartments = [
  [
    'title' => 'Villetta delle Rose',
    'cover' => 'https://octorate.com/wordpress/wp-content/uploads/2022/02/siti-come-airbnb-migliori-siti-per-affittare-case-vacanze.webp',
    'is_visible' => true,
    'rooms' => 4,
    'beds' => 8,
    'bathrooms' => 3,
    'sqm' => 180,
    'address' => 'Via dei Girasoli 10, Roma, Italia',
    'latitude' => 41.9109,
    'longitude' => 12.4818,
  ],
  [
    'title' => 'Casa Bella Vista',
    'cover' => 'https://example.com/images/casa_bella_vista.jpg',
    'is_visible' => true,
    'rooms' => 3,
    'beds' => 6,
    'bathrooms' => 2,
    'sqm' => 120,
    'address' => 'Via del Corallo 25, Roma, Italia',
    'latitude' => 41.8974,
    'longitude' => 12.4802,
  ],
  [
    'title' => 'Appartamento del Trastevere',
    'cover' => 'https://example.com/images/appartamento_del_trastevere.jpg',
    'is_visible' => true,
    'rooms' => 2,
    'beds' => 4,
    'bathrooms' => 1,
    'sqm' => 85,
    'address' => 'Via della Lungara 100, Roma, Italia',
    'latitude' => 41.8956,
    'longitude' => 12.4666,
  ],
  [
    'title' => 'Villa dei Fiori',
    'cover' => 'https://example.com/images/villa_dei_fiori.jpg',
    'is_visible' => true,
    'rooms' => 5,
    'beds' => 10,
    'bathrooms' => 4,
    'sqm' => 220,
    'address' => 'Via Salaria 150, Roma, Italia',
    'latitude' => 41.9151,
    'longitude' => 12.4944,
  ],
  [
    'title' => 'Casetta Romantica',
    'cover' => 'https://example.com/images/casetta_romantica.jpg',
    'is_visible' => true,
    'rooms' => 1,
    'beds' => 2,
    'bathrooms' => 1,
    'sqm' => 60,
    'address' => 'Via delle Querce 5, Roma, Italia',
    'latitude' => 41.8951,
    'longitude' => 12.4804,
  ],
];
