<?php

/* APPARTAMENTI */

return $apartments = [
  [
    'title' => 'Villa Le Rose',
    'user_id' => 1,
    'description' => 'Elegante villa con giardino privato e vista panoramica sulla città. Spazi ampi e luminosi, arredamento di lusso e atmosfera raffinata.',
    'cover' => 'https://a0.muscache.com/im/pictures/miso/Hosting-908520646530600248/original/d2486b1f-656a-431e-86cb-6ed887ded5a8.jpeg?im_w=1200',
    'is_visible' => true,
    'rooms' => 3,
    'beds' => 4,
    'bathrooms' => 3,
    'sqm' => 200,
    'address' => 'Via Appia 10, Roma, Italia',
    'latitude' => 41.8837,
    'longitude' => 12.4861
  ],
  ['title' => 'Villa Infinity', 'user_id' => 1, 'description' => 'Incantevole mansarda nel cuore di Roma, con terrazza panoramica e vista sui tetti della città. Ideale per una vacanza romantica.', 'cover' => 'https://a0.muscache.com/im/pictures/prohost-api/Hosting-957819679097220222/original/53afb9d5-777e-46bf-b657-36cd979bddc8.jpeg?im_w=1200', 'is_visible' => true, 'rooms' => 1, 'beds' => 1, 'bathrooms' => 1, 'sqm' => 50, 'address' => 'Via Giulia 20, Roma, Italia', 'latitude' => 41.8962, 'longitude' => 12.4689],
  ['title' => 'Appartamento Storico', 'user_id' => 1, 'description' => 'Accogliente appartamento in un palazzo storico nel centro di Roma. Arredamento classico e atmosfera suggestiva, a pochi passi dai principali monumenti.', 'cover' => 'https://www.maxlisiphotographer.com/wp-content/uploads/2020/06/MG_8550-HDR.jpg', 'is_visible' => true, 'rooms' => 2, 'beds' => 3, 'bathrooms' => 2, 'sqm' => 80, 'address' => 'Via del Corso 15, Roma, Italia', 'latitude' => 41.8954, 'longitude' => 12.4765],
  ['title' => 'Loft Moderno', 'user_id' => 1, 'description' => 'Spazioso loft dal design contemporaneo, con ampie vetrate e terrazza con vista sulla città. Perfetto per chi ama lo stile minimalista.', 'cover' => 'https://th.bing.com/th/id/OIP.cq4_gAAMIv9MJLyvzTn2KQHaFQ?rs=1&pid=ImgDetMain', 'is_visible' => true, 'rooms' => 1, 'beds' => 2, 'bathrooms' => 1, 'sqm' => 70, 'address' => 'Via Veneto 30, Roma, Italia', 'latitude' => 41.9055, 'longitude' => 12.4884],
  ['title' => 'Casa Panoramica', 'user_id' => 1, 'description' => 'Panoramica casa con vista su Piazza di Spagna e Trinità dei Monti. Arredo moderno e comfort di alto livello, ideale per una vacanza di lusso.', 'cover' => 'https://th.bing.com/th/id/OIP.QY6Hk7p44uOrIp__hyYh0AHaDb?rs=1&pid=ImgDetMain', 'is_visible' => true, 'rooms' => 2, 'beds' => 4, 'bathrooms' => 3, 'sqm' => 120, 'address' => 'Piazza di Spagna 5, Roma, Italia', 'latitude' => 41.9054, 'longitude' => 12.4823],
  ['title' => 'Attico Luminoso', 'user_id' => 1, 'description' => 'Elegante attico con terrazza panoramica e vista sui monumenti di Roma. Arredamento di design e comfort di lusso.', 'cover' => 'https://images2-wpc.corriereobjects.it/LS42fp5cVVf5rsMhjLEic_d_jFM=/fit-in/1120x653/style.corriere.it/assets/uploads/2019/01/terrace02.jpg', 'is_visible' => true, 'rooms' => 3, 'beds' => 3, 'bathrooms' => 2, 'sqm' => 150, 'address' => 'Via del Tritone 25, Roma, Italia', 'latitude' => 41.8996, 'longitude' => 12.4837],
  ['title' => 'Villetta Confortevole', 'user_id' => 1, 'description' => 'Villetta con giardino e terrazza in una zona tranquilla di Roma. Ideale per famiglie o gruppi di amici in cerca di relax.', 'cover' => 'https://www.contocorrenteonline.it/wp-content/uploads/2021/05/villa.jpg', 'is_visible' => true, 'rooms' => 3, 'beds' => 6, 'bathrooms' => 2, 'sqm' => 100, 'address' => 'Via Appia Nuova 40, Roma, Italia', 'latitude' => 41.8682, 'longitude' => 12.5239],
  ['title' => 'Stanza Deluxe', 'user_id' => 1, 'description' => 'Stanza di lusso in elegante palazzo nel centro storico di Roma. Arredo raffinato e servizi esclusivi per un soggiorno indimenticabile.', 'cover' => 'https://th.bing.com/th/id/OIP.CNl9aXTXdHKwrWMUgTMSpAHaEO?rs=1&pid=ImgDetMain', 'is_visible' => true, 'rooms' => 1, 'beds' => 1, 'bathrooms' => 1, 'sqm' => 30, 'address' => 'Via dei Condotti 22, Roma, Italia', 'latitude' => 41.9061, 'longitude' => 12.4832],
  ['title' => 'Palazzina Storica', 'user_id' => 1, 'description' => 'Appartamento in una palazzina storica nel centro di Roma, con affreschi e soffitti alti. Un tuffo nella storia della città eterna.', 'cover' => 'https://th.bing.com/th/id/R.271b19719abf2fddc3a338f2118b886f?rik=%2f1AKCZlb2v8s6A&riu=http%3a%2f%2f2night.s3.amazonaws.com%2fpics%2farticles%2fcropped%2f1600x800%2fd68%2f54c6864985c759030e83b118.jpg&ehk=K2qABB9PqK7gmqyoM0giy%2f21a50sRWh%2bny%2fGIQQC3d0%3d&risl=&pid=ImgRaw&r=0', 'is_visible' => true, 'rooms' => 3, 'beds' => 3, 'bathrooms' => 2, 'sqm' => 90, 'address' => 'Via Giulia 30, Roma, Italia', 'latitude' => 41.8959, 'longitude' => 12.4685],
  [
    'title' => 'Villetta delle Rose',
    'user_id' => 1,
    'description' => 'Affascinante loft nel cuore della città, con travi a vista e una vista panoramica che abbraccia i tetti antichi. Perfetto per una fuga romantica, offre un\'atmosfera intima e accogliente, arricchita da dettagli storici e moderni comfort.',
    'cover' => 'https://octorate.com/wordpress/wp-content/uploads/2022/02/siti-come-airbnb-migliori-siti-per-affittare-case-vacanze.webp',
    'is_visible' => true,
    'rooms' => 4,
    'beds' => 8,
    'bathrooms' => 3,
    'sqm' => 180,
    'address' => 'Via dei Girasoli 10, Roma, Italia',
    'latitude' => 41.9109,
    'longitude' => 12.4818,
  ],
  [
    'title' => 'Casa Bella Vista',
    'user_id' => 1,
    'description' => 'Monolocale moderno con una terrazza privata che si affaccia sul mare cristallino, regalando tramonti mozzafiato e momenti di puro relax. Ideale per una vacanza tranquilla, offre la possibilità di godere della brezza marina e dell\'atmosfera mediterranea.',
    'cover' => 'https://www.miprendoemiportovia.it/wp-content/uploads/2020/10/Casa-Nea-Sardegna.jpg',
    'is_visible' => true,
    'rooms' => 3,
    'beds' => 6,
    'bathrooms' => 2,
    'sqm' => 120,
    'address' => 'Via del Corallo 25, Roma, Italia',
    'latitude' => 41.8974,
    'longitude' => 12.4802,
  ],
  [
    'title' => 'Appartamento del Trastevere',
    'user_id' => 1,
    'description' => 'Appartamento nel cuore del centro storico, arricchito da un camino e arredi rustici che creano un\'atmosfera calda e autentica. Perfetto per chi desidera vivere un\'esperienza immersiva nel tessuto storico della città, con tutti i comfort moderni a portata di mano.',
    'cover' => 'https://i.pinimg.com/564x/a9/54/0b/a9540ba59ab48369fcb847eec1393084.jpg',
    'is_visible' => true,
    'rooms' => 2,
    'beds' => 4,
    'bathrooms' => 1,
    'sqm' => 85,
    'address' => 'Via della Lungara 100, Roma, Italia',
    'latitude' => 41.8956,
    'longitude' => 12.4666,
  ],
  [
    'title' => 'Villa dei Fiori',
    'user_id' => 1,
    'description' => 'Un loft minimalista dal design contemporaneo, caratterizzato da spazi luminosi e ampie finestre che offrono una vista mozzafiato sulla città. Con soffitti alti e arredi moderni, è l\'ideale per chi ama lo stile urbano e la comodità di un ambiente raffinato.',
    'cover' => 'https://i.pinimg.com/736x/62/99/1b/62991bce34667995c52a33da134383b4.jpg',
    'is_visible' => true,
    'rooms' => 5,
    'beds' => 10,
    'bathrooms' => 4,
    'sqm' => 220,
    'address' => 'Via Salaria 150, Roma, Italia',
    'latitude' => 41.9151,
    'longitude' => 12.4944,
  ],
  [
    'title' => 'Casetta Romantica',
    'user_id' => 1,
    'description' => 'Circondato da giardini rigogliosi e alberi secolari, questo appartamento immerso nel verde è un\'oasi di pace e tranquillità. Perfetto per una pausa rigenerante dalla frenesia cittadina, offre la possibilità di riconnettersi con la natura senza rinunciare al comfort della vita moderna. Con spazi luminosi e arredi accoglienti, è il rifugio ideale per rigenerare mente e corpo.',
    'cover' => 'https://st3.idealista.it/news/archivie/styles/open_graph/public/2017-09/houzz1.png?VersionId=A9xFG2zFuIbLdOvphoG8GYWzELhuDMRT&itok=27me4Oe_',
    'is_visible' => true,
    'rooms' => 1,
    'beds' => 2,
    'bathrooms' => 1,
    'sqm' => 60,
    'address' => 'Via delle Querce 5, Roma, Italia',
    'latitude' => 41.8951,
    'longitude' => 12.4804,
  ],
];
