<?php
return $apartments = [
  [
    'title' => 'Villetta delle Rose',
    'description' => 'Affascinante loft nel cuore della città, con travi a vista e una vista panoramica che abbraccia i tetti antichi. Perfetto per una fuga romantica, offre un\'atmosfera intima e accogliente, arricchita da dettagli storici e moderni comfort.',
    'cover' => 'https://octorate.com/wordpress/wp-content/uploads/2022/02/siti-come-airbnb-migliori-siti-per-affittare-case-vacanze.webp',
    'is_visible' => true,
    'rooms' => 4,
    'beds' => 8,
    'bathrooms' => 3,
    'sqm' => 180,
    'address' => 'Via dei Girasoli 10, Roma, Italia',
    'latitude' => 41.9109,
    'longitude' => 12.4818,
  ],
  [
    'title' => 'Casa Bella Vista',
    'description' => 'Monolocale moderno con una terrazza privata che si affaccia sul mare cristallino, regalando tramonti mozzafiato e momenti di puro relax. Ideale per una vacanza tranquilla, offre la possibilità di godere della brezza marina e dell\'atmosfera mediterranea.',
    'cover' => 'https://www.miprendoemiportovia.it/wp-content/uploads/2020/10/Casa-Nea-Sardegna.jpg',
    'is_visible' => true,
    'rooms' => 3,
    'beds' => 6,
    'bathrooms' => 2,
    'sqm' => 120,
    'address' => 'Via del Corallo 25, Roma, Italia',
    'latitude' => 41.8974,
    'longitude' => 12.4802,
  ],
  [
    'title' => 'Appartamento del Trastevere',
    'description' => 'Appartamento nel cuore del centro storico, arricchito da un camino e arredi rustici che creano un\'atmosfera calda e autentica. Perfetto per chi desidera vivere un\'esperienza immersiva nel tessuto storico della città, con tutti i comfort moderni a portata di mano.',
    'cover' => 'https://i.pinimg.com/564x/a9/54/0b/a9540ba59ab48369fcb847eec1393084.jpg',
    'is_visible' => true,
    'rooms' => 2,
    'beds' => 4,
    'bathrooms' => 1,
    'sqm' => 85,
    'address' => 'Via della Lungara 100, Roma, Italia',
    'latitude' => 41.8956,
    'longitude' => 12.4666,
  ],
  [
    'title' => 'Villa dei Fiori',
    'description' => 'Un loft minimalista dal design contemporaneo, caratterizzato da spazi luminosi e ampie finestre che offrono una vista mozzafiato sulla città. Con soffitti alti e arredi moderni, è l\'ideale per chi ama lo stile urbano e la comodità di un ambiente raffinato.',
    'cover' => 'https://i.pinimg.com/736x/62/99/1b/62991bce34667995c52a33da134383b4.jpg',
    'is_visible' => true,
    'rooms' => 5,
    'beds' => 10,
    'bathrooms' => 4,
    'sqm' => 220,
    'address' => 'Via Salaria 150, Roma, Italia',
    'latitude' => 41.9151,
    'longitude' => 12.4944,
  ],
  [
    'title' => 'Casetta Romantica',
    'description' => 'Circondato da giardini rigogliosi e alberi secolari, questo appartamento immerso nel verde è un\'oasi di pace e tranquillità. Perfetto per una pausa rigenerante dalla frenesia cittadina, offre la possibilità di riconnettersi con la natura senza rinunciare al comfort della vita moderna. Con spazi luminosi e arredi accoglienti, è il rifugio ideale per rigenerare mente e corpo.',
    'cover' => 'https://st3.idealista.it/news/archivie/styles/open_graph/public/2017-09/houzz1.png?VersionId=A9xFG2zFuIbLdOvphoG8GYWzELhuDMRT&itok=27me4Oe_',
    'is_visible' => true,
    'rooms' => 1,
    'beds' => 2,
    'bathrooms' => 1,
    'sqm' => 60,
    'address' => 'Via delle Querce 5, Roma, Italia',
    'latitude' => 41.8951,
    'longitude' => 12.4804,
  ],
];
